language: android

jdk: oraclejdk8

env:
  matrix:
    - ANDROID_TARGET=android-27 ANDROID_ABI=armeabi-v7a
  global:
    secure: "ApyKVMXFmi442hy9J3r8fTotPOGwnoP/fFSsBWbjfOMm9RfMQHdFqTOLasyP1kuUMZZ/aAiUrwwT7vu6TsH3eUvBKI8uJdtGN3sShpKiwSTWnJWsGB6R05e8ThJbOGNrXMNvHXvQrole4GqHiCtS1gSWBIgQJYqlepn/fDVN9dyyhf9Hx8XvoasN6+WeqIBeSreY7LmqcpnheeAoQYHfe42SSRJVh7K6o1RqpQwnoOJLDaE1MnrjEaSddzKwcvrpXljttZhOlWAAXqsaOE3s4u8Nwo8+eRlDOKetck/R88DO92Q6vdpgQ1543lODHSv6lBvdo5Ynenbm5yfL3LJgYmBihyhXi9kysmLIpgKHqSvr8gSSJp1qS5DEMf85mtS1TDS5GjhipDQy2mzlb3rCrSEQWF2MjwIGoeSvsXuumbDrI4Ouo90jEAdqhCu2i2lFOA7ChR5idfvUlQceD5S/ZmyPwD2+OrTsbn4HjlChtGcZhVo4j0mdTLf9paGCuHY9no6fUhp42z38jzaOp39J5Dfj6LWejPbrDGpmm3Q7xRvuQIoT5NZFPZ2rDPuJUAtCpZ2+zS3Lu2NMTIZA3NB90T/6h3CghaQEXT8qOlGKBh94mo7L9t8OyMgsdJw0T+msB2Gf0fB8hocdmtfcMYnGHQNO+ON4cIzVkAlsf5lK2Ag="

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-27
    - extra-android-support
  licenses:
    - android-sdk-preview-license-52d11cd2
    - android-sdk-license-.+
    - google-gdk-license-.+

before_script:
  - export WRK_DIR=$(pwd)
  - echo WRK_DIR is $WRK_DIR
  - cd ${WRK_DIR}/android/TMHarness/TMHarnessUX
  - echo MBGL_API_ACCESS_TOKEN is "${MBGL_API_ACCESS_TOKEN}"
  - sed -i "s/YOUR_MAPBOX_API_ACCESS_TOKEN/${MBGL_API_ACCESS_TOKEN}/g" mbgl.properties
  - cat mbgl.properties
  - cd ${WRK_DIR}/android/TMHarness
  - chmod +x ./gradlew

script:
  - "./gradlew build"
